"""add stay_type to trips

Revision ID: b50322844dfa
Revises: de0d26fbce44
Create Date: 2026-07-28 08:23:41.250571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50322844dfa'
down_revision: Union[str, None] = 'de0d26fbce44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # autogenerate's add_column doesn't create the backing enum type on its
    # own (unlike create_table) -- create it explicitly first.
    stay_type_enum = sa.Enum('camping', 'stallplats', 'fricamping', name='stay_type')
    stay_type_enum.create(op.get_bind())
    op.add_column('trips', sa.Column('stay_type', stay_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'stay_type')
    sa.Enum(name='stay_type').drop(op.get_bind())
    # ### end Alembic commands ###
